import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--epoch', type=int, default=150, help='epoch number')  #150√ 200
parser.add_argument('--model_name', type=str, default="LF", help='model name')
parser.add_argument('--lr', type=float, default=5e-5, help='learning rate')#5e-5
parser.add_argument('--batchsize', type=int, default=4, help='training batch size')
parser.add_argument('--trainsize', type=int, default=256, help='training dataset size')
parser.add_argument('--clip', type=float, default=0.5, help='gradient clipping margin')
parser.add_argument('--decay_rate', type=float, default=0.1, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=100, help='every n epochs decay learning rate')
parser.add_argument('--load_mit', type=str, default='./pretrained_params/mambavision_tiny_1k.pth.tar', help='train from checkpoints')
parser.add_argument('--gpu_id', type=str, default='3', help='train use gpu')
parser.add_argument('--rgb_root', type=str, default='./dataset/train/train_images/', help='the training rgb images root')
parser.add_argument('--fs_root', type=str, default='./dataset/train/train_focals/', help='the training depth images root')
parser.add_argument('--gt_root', type=str, default='./dataset/train/train_masks/', help='the training gt images root')
parser.add_argument('--depth_root', type=str, default='./dataset/train/train_depths/', help='the training depth images root')
parser.add_argument('--edgein_root', type=str, default='./dataset/train/train_edge_internal/', help='the training edgein images root')
parser.add_argument('--edgeex_root', type=str, default='./dataset/train/train_edge_external/', help='the training edgeex images root')
parser.add_argument('--test_rgb_root', type=str, default='./dataset/test/Lytro-Illum/test_images/', help='the test rgb images root')
parser.add_argument('--test_fs_root', type=str, default='./dataset/test/Lytro-Illum/test_focals/', help='the test fs images root')
parser.add_argument('--test_gt_root', type=str, default='./dataset/test/Lytro-Illum/test_masks/', help='the test gt images root')
parser.add_argument('--test_depth_root', type=str, default='./dataset/test/Lytro-Illum/test_depths/', help='the test gt images root')
parser.add_argument('--save_path', type=str, default='./lfsod_savepath/', help='the path to save models and logs')
parser.add_argument('--resume', type=bool, default=False, help='when project break,wheather or not to continue')
opt = parser.parse_args()